#!/bin/sh

echo "Booting from SD"

if [ ! -e /dev/mmc1.0 ]; then
	echo "Boot partition not found!"
	exit 1
fi

if [ -f /mnt/mmc1.0/zImage ]; then
	global bootm.image="/mnt/mmc1.0/zImage"
	global.linux.bootargs.dyn.root="root=/dev/mmcblk1p2 rw rootwait"

	DTB=/mnt/mmc1.0/mm-sm-sama5d2-evb.dtb
else
	echo "Boot image not found!"
	exit 1
fi

if [ -f $DTB ]; then
	echo "Using external devicetree blob from $DTB"
	global.bootm.oftree=$DTB
else
	echo "Using internal devicetree blob"
fi

exit 0
