#!/bin/sh

if [ "$1" = menu ]; then
	init-menu-add-entry "$0" "NAND partitions"
	exit
fi

mtdparts="512k(boot)ro,256k(env),3328k(kernel),28672k(root),-(bbox)"
kernelname="mxc_nand"

mtdparts-add -b -d nand0 -k ${kernelname} -p ${mtdparts}
